"""p1.3: secure email account foundation

Revision ID: 1e7ab6ba0976
Revises: 61258798a87a
Create Date: 2026-09-07 20:07:43.995363

P1.3 schema change. Purely additive on top of the P1.2 revision
(61258798a87a) -- one new table, no existing table is touched, no
existing row is modified.

What this adds, and why:

- `email_accounts` (new table, many-to-one with `organizations`) -- an
  organization-scoped sender mailbox: connection metadata plus an
  *encrypted* credential and a verification status. This is the secure
  foundation P1.4 (real outreach sending) will build on top of; P1.3 does
  not send any email. See core/domain/models/email_account.py for the
  full column-by-column design rationale.

Notable constraints (all reviewed by hand, none blindly accepted from
autogenerate's output):

- `uq_email_accounts_org_email` -- UNIQUE(organization_id, email_address).
  Deliberately organization-scoped, not a global UNIQUE(email_address):
  the same email address can legitimately be a sender mailbox for two
  different organizations.
- `ck_email_accounts_smtp_port_range` -- CHECK(smtp_port BETWEEN 1 AND
  65535). A valid TCP port is a structural invariant, not a business
  rule, so it's enforced in the database, not only in the Pydantic schema
  (core/domain/schemas/email_account.py validates the same range at the
  point of user input; the CHECK is the backstop). Deliberately NOT doing
  the same for credential_type/verification_status/security_mode: those
  are intentionally plain, unconstrained strings so a future value (e.g.
  an OAuth credential_type in a later phase) is an additive,
  zero-migration change -- a CHECK enumerating today's exact allowed
  values would defeat that.
- `ix_email_accounts_organization_id` -- every ownership-check/list query
  filters on this.
- `ix_email_accounts_org_active` -- composite (organization_id,
  is_active), supporting the one additional real access pattern: listing
  only the currently-usable accounts for an organization (this phase's
  own list endpoint's common case of hiding disabled accounts, and P1.4's
  future sender-selection query).

SECURITY: `encrypted_credential` is a plain String column holding Fernet
ciphertext (see core/infrastructure/security/credential_crypto.py) -- it
is NEVER plaintext at rest, and this migration file itself contains no
credential, no encryption key, and no other secret, per the P1.3 brief.

Autogenerated against a from-scratch SQLite copy of the P1.1+P1.2 chain
(no live PostgreSQL instance was available in this environment -- see the
final P1.3 report for exactly what was and wasn't run against real
PostgreSQL), then hand-reviewed and hand-corrected: autogenerate captured
`created_at`'s server_default using SQLite's `CURRENT_TIMESTAMP` syntax;
corrected below to `now()` to match every other table in this project's
actual database, PostgreSQL (same correction the P1.2 migration's
docstring documents making for the same reason). No other change was made
to the raw autogenerate output -- every operation is create_table/
create_index, no drops, no ALTERs to any existing table.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7ab6ba0976'
down_revision: Union[str, Sequence[str], None] = '61258798a87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('smtp_host', sa.String(), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('security_mode', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credential_type', sa.String(), nullable=False),
    sa.Column('encrypted_credential', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_error_code', sa.String(), nullable=True),
    # NOTE: hand-corrected from autogenerate's SQLite-flavored
    # sa.text('(CURRENT_TIMESTAMP)') to now() -- see this file's module
    # docstring.
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('smtp_port > 0 AND smtp_port <= 65535', name='ck_email_accounts_smtp_port_range'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email_address', name='uq_email_accounts_org_email')
    )
    op.create_index(op.f('ix_email_accounts_id'), 'email_accounts', ['id'], unique=False)
    op.create_index('ix_email_accounts_org_active', 'email_accounts', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_email_accounts_organization_id'), 'email_accounts', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_accounts_organization_id'), table_name='email_accounts')
    op.drop_index('ix_email_accounts_org_active', table_name='email_accounts')
    op.drop_index(op.f('ix_email_accounts_id'), table_name='email_accounts')
    op.drop_table('email_accounts')
    # ### end Alembic commands ###
