"""p1.4: outreach action and mailing agent contract

Revision ID: baee12037c73
Revises: 1e7ab6ba0976
Create Date: 2026-09-10 23:04:02.258598

P1.4 schema change. Purely additive on top of the P1.3 revision
(1e7ab6ba0976) -- two new tables, no existing table is touched, no
existing row is modified.

What this adds, and why:

- `outreach_actions` (new table) -- the LeadBoost-owned authorization/
  audit boundary between lead intelligence + message generation and the
  separate Mailing Agent service. See core/domain/models/outreach_action.py
  for the full column-by-column design rationale, including why this
  table snapshots subject/body immutably instead of referencing the lead
  live, and why it has no credential-shaped column at all.

- `organization_outreach_policies` (new table, one-to-one with
  `organizations`) -- the persisted, explicit "customer safety policy"
  gating AUTOMATIC-mode outreach, following the exact same one-row-per-
  organization pattern as `organization_qualification_settings` (P1.2).
  See core/domain/models/outreach_policy.py.

Notable constraints (all reviewed by hand, none blindly accepted from
autogenerate's output):

- `uq_outreach_actions_org_idempotency_key` -- UNIQUE(organization_id,
  idempotency_key). This is the actual, race-proof idempotency guarantee
  (application/services/outreach_service.py's own pre-check is only an
  optimization) -- see that module's docstring for how the key is
  derived when a caller doesn't supply one, and
  core/infrastructure/mailing_agent/CONTRACT.md for why the same key is
  also a hard requirement of the Mailing Agent's own side of the
  contract.
- `ix_outreach_actions_org_state` / `ix_outreach_actions_org_lead` --
  composite indexes supporting this phase's two real access patterns:
  listing an organization's actions filtered by state, and listing an
  organization's actions for one lead.
- Deliberately NO CheckConstraint enumerating `mode` or `state`'s
  allowed values, for the same reason P1.3's migration left
  credential_type/verification_status unconstrained: both are validated
  at the Pydantic/service layer, and a future additional state should be
  able to land as an additive, zero-migration change. This paid off
  immediately: `state` gained a `dispatching` value (the atomic
  dispatch-claim state -- see OutreachState's docstring) after this
  table was first designed, with no migration required at all.
- `ck_outreach_policy_*` range/non-negativity checks on
  `organization_outreach_policies` mirror
  `ck_email_accounts_smtp_port_range`'s reasoning: these are structural
  invariants (a send limit can't be negative, an hour-of-day can't be 24),
  not business rules, so they're backstopped in the database in addition
  to core/domain/schemas/outreach_policy.py's identical validation at the
  point of user input.

SECURITY: neither table has any column that could hold a credential,
plaintext or encrypted -- `outreach_actions` references its sender only
by `email_account_id`, never duplicating any part of
`email_accounts.encrypted_credential`. This migration file itself
contains no credential, no encryption key, and no other secret.

Autogenerated against a from-scratch SQLite copy of the P1.1+P1.2+P1.3
chain (no live PostgreSQL instance was available in this environment --
same limitation the P1.3 migration's docstring documents, for the same
reason), then hand-reviewed and hand-corrected: autogenerate captured
both tables' `created_at` using SQLite's `CURRENT_TIMESTAMP` syntax;
corrected below to `now()` to match every other table in this project's
actual database, PostgreSQL. No other change was made to the raw
autogenerate output -- every operation is create_table/create_index, no
drops, no ALTERs to any existing table.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baee12037c73'
down_revision: Union[str, Sequence[str], None] = '1e7ab6ba0976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_outreach_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('automatic_sending_enabled', sa.Boolean(), nullable=False),
    sa.Column('require_approval_for_automatic', sa.Boolean(), nullable=False),
    sa.Column('daily_send_limit', sa.Integer(), nullable=True),
    sa.Column('hourly_send_limit', sa.Integer(), nullable=True),
    sa.Column('sending_window_start_hour_utc', sa.Integer(), nullable=True),
    sa.Column('sending_window_end_hour_utc', sa.Integer(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    # NOTE: hand-corrected from autogenerate's SQLite-flavored
    # sa.text('(CURRENT_TIMESTAMP)') to now() -- see this file's module
    # docstring and the same correction in the P1.3 migration.
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('daily_send_limit IS NULL OR daily_send_limit >= 0', name='ck_outreach_policy_daily_limit_nonneg'),
    sa.CheckConstraint('hourly_send_limit IS NULL OR hourly_send_limit >= 0', name='ck_outreach_policy_hourly_limit_nonneg'),
    sa.CheckConstraint('sending_window_end_hour_utc IS NULL OR (sending_window_end_hour_utc >= 0 AND sending_window_end_hour_utc <= 23)', name='ck_outreach_policy_window_end_range'),
    sa.CheckConstraint('sending_window_start_hour_utc IS NULL OR (sending_window_start_hour_utc >= 0 AND sending_window_start_hour_utc <= 23)', name='ck_outreach_policy_window_start_range'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_outreach_policies_id'), 'organization_outreach_policies', ['id'], unique=False)
    op.create_index(op.f('ix_organization_outreach_policies_organization_id'), 'organization_outreach_policies', ['organization_id'], unique=True)
    op.create_table('outreach_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('email_account_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mailing_agent_reference', sa.String(), nullable=True),
    sa.Column('dispatch_attempts', sa.Integer(), nullable=False),
    sa.Column('last_dispatch_error', sa.String(), nullable=True),
    # NOTE: hand-corrected from autogenerate's SQLite-flavored
    # sa.text('(CURRENT_TIMESTAMP)') to now() -- see this file's module
    # docstring and the same correction in the P1.3 migration.
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_accounts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_outreach_actions_org_idempotency_key')
    )
    op.create_index(op.f('ix_outreach_actions_correlation_id'), 'outreach_actions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_outreach_actions_email_account_id'), 'outreach_actions', ['email_account_id'], unique=False)
    op.create_index(op.f('ix_outreach_actions_id'), 'outreach_actions', ['id'], unique=False)
    op.create_index(op.f('ix_outreach_actions_idempotency_key'), 'outreach_actions', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_outreach_actions_lead_id'), 'outreach_actions', ['lead_id'], unique=False)
    op.create_index('ix_outreach_actions_org_lead', 'outreach_actions', ['organization_id', 'lead_id'], unique=False)
    op.create_index('ix_outreach_actions_org_state', 'outreach_actions', ['organization_id', 'state'], unique=False)
    op.create_index(op.f('ix_outreach_actions_organization_id'), 'outreach_actions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_outreach_actions_state'), 'outreach_actions', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_actions_state'), table_name='outreach_actions')
    op.drop_index(op.f('ix_outreach_actions_organization_id'), table_name='outreach_actions')
    op.drop_index('ix_outreach_actions_org_state', table_name='outreach_actions')
    op.drop_index('ix_outreach_actions_org_lead', table_name='outreach_actions')
    op.drop_index(op.f('ix_outreach_actions_lead_id'), table_name='outreach_actions')
    op.drop_index(op.f('ix_outreach_actions_idempotency_key'), table_name='outreach_actions')
    op.drop_index(op.f('ix_outreach_actions_id'), table_name='outreach_actions')
    op.drop_index(op.f('ix_outreach_actions_email_account_id'), table_name='outreach_actions')
    op.drop_index(op.f('ix_outreach_actions_correlation_id'), table_name='outreach_actions')
    op.drop_table('outreach_actions')
    op.drop_index(op.f('ix_organization_outreach_policies_organization_id'), table_name='organization_outreach_policies')
    op.drop_index(op.f('ix_organization_outreach_policies_id'), table_name='organization_outreach_policies')
    op.drop_table('organization_outreach_policies')
    # ### end Alembic commands ###
