"""p1.2: company profile, qualification settings, sender profile

Revision ID: 61258798a87a
Revises: eaa40e596fcc
Create Date: 2026-09-06 02:51:44.274672

P1.2 schema change. Purely additive on top of the P1.1 baseline
(eaa40e596fcc) -- no existing table is altered destructively, no existing
column is dropped or retyped, and no existing row is modified.

What this adds, and why:

1. `organization_qualification_settings` (new table, 1:1 with
   `organizations` via a unique FK) -- the organization-scoped
   qualification *policy* (`qualification_threshold`, 0-100, same scale as
   the existing `leads.score`) that this product previously had no way to
   configure per tenant at all: "qualified" was only ever the hardcoded
   80/60/40 cutoff baked into
   core.domain.services.scoring.LeadScoringService._classify_lead, which
   is left completely unchanged by this migration -- see
   core/domain/models/qualification_settings.py for the full design
   rationale.

2. `organizations.industry`, `organizations.icp_description` (new nullable
   columns) -- minimal Company Profile fields. `organizations.name` and
   `.description` already existed and are reused as-is, not duplicated.

3. `users.job_title`, `users.signature` (new nullable columns) -- minimal
   Sender Profile fields, extending the user's existing personal-identity
   columns (first_name/last_name/email) the same way industry/
   icp_description extend Organization's existing name/description.

No existing organization is left with an unusable/undefined qualification
policy: rather than eagerly writing a default-threshold row for every
existing organization here (a migration-time write whose cost scales with
table size, for a value that is only ever read, never joined/filtered
on by other tables), `get_or_create_qualification_settings()` in
core/infrastructure/database/crud.py lazily creates the row with
DEFAULT_QUALIFICATION_THRESHOLD (60.0, matching the existing "Warm Lead"
cutoff) on first read for that organization. Every read path in this
change goes through that one function, so no code path can observe a
missing settings row as an undefined/NULL threshold.

Autogenerated against a from-scratch SQLite copy of the P1.1 baseline
(no live PostgreSQL instance was available in this environment -- see the
final P1.2 report for exactly what was and wasn't run against real
PostgreSQL), then hand-reviewed and hand-corrected: autogenerate captured
`created_at`'s server_default using SQLite's `CURRENT_TIMESTAMP` syntax;
corrected below to `now()` to match every other table in the P1.1
baseline (all of which target PostgreSQL, this project's actual database).
No other change was made to the raw autogenerate output -- every operation
is create_table/create_index/add_column, no drops, matching the
"additive-only" bar the baseline revision itself documents.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61258798a87a'
down_revision: Union[str, Sequence[str], None] = 'eaa40e596fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_qualification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('qualification_threshold', sa.Float(), nullable=False),
    # NOTE: hand-corrected from autogenerate's SQLite-flavored
    # `sa.text('(CURRENT_TIMESTAMP)')` to `now()`, matching every other
    # table's created_at in the P1.1 baseline revision (this project's
    # real database is PostgreSQL -- see this file's module docstring).
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('qualification_threshold >= 0.0 AND qualification_threshold <= 100.0', name='ck_qualification_threshold_range'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_qualification_settings_id'), 'organization_qualification_settings', ['id'], unique=False)
    op.create_index(op.f('ix_organization_qualification_settings_organization_id'), 'organization_qualification_settings', ['organization_id'], unique=True)
    op.add_column('organizations', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('icp_description', sa.String(), nullable=True))
    op.add_column('users', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('users', sa.Column('signature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signature')
    op.drop_column('users', 'job_title')
    op.drop_column('organizations', 'icp_description')
    op.drop_column('organizations', 'industry')
    op.drop_index(op.f('ix_organization_qualification_settings_organization_id'), table_name='organization_qualification_settings')
    op.drop_index(op.f('ix_organization_qualification_settings_id'), table_name='organization_qualification_settings')
    op.drop_table('organization_qualification_settings')
    # ### end Alembic commands ###
