"""baseline: adopt current schema (P0 + observability)

Revision ID: eaa40e596fcc
Revises:
Create Date: 2026-09-05 20:01:37.094362

P1.1 baseline / adoption revision.
===================================
This is the FIRST Alembic revision for LeadBoost. It is not an ordinary
incremental migration -- it captures the entire schema as it already
exists today (18 tables: the 14 registered by core.domain.models plus the
4 in application.observability.models -- see alembic/env.py's docstring
for why both must be imported). Raw, unmodified `alembic revision
--autogenerate` output against an empty PostgreSQL database, reviewed by
hand: every operation in upgrade() is additive (create_table/create_index
only -- no drops, no destructive ALTERs); downgrade() is the symmetric
full teardown, appropriate only because this is the very first revision.

Two different situations use this revision differently:

* Fresh/empty database (new dev environment, CI, a new deployment target):
  run `alembic upgrade head` normally. This revision executes for real and
  creates the schema from nothing.

* An existing database that was already built by `Base.metadata.create_all()`
  (every LeadBoost database up to and including P0 -- see
  backend/migrations/001_p0_durable_execution.sql, which upgraded an
  earlier pre-P0 create_all()-built schema to the current shape, and is
  preserved as historical documentation, not a competing migration tool):
  do NOT run `alembic upgrade head` against it -- every `CREATE TABLE`
  here would fail against tables that already exist. Instead:
    1. verify the database's actual schema matches this revision (see
       backend/scripts/verify_baseline_schema.py -- checks table/column/
       constraint presence, including uq_leads_org_website and every P0
       column named in 001_p0_durable_execution.sql)
    2. only if that verification passes: `alembic stamp eaa40e596fcc`
       (records "already at this revision", executes zero DDL)
    3. `alembic upgrade head` is then a no-op (already at head)
  If verification fails, the database does NOT match this baseline and
  must not be stamped -- see docs/DEPLOYMENT.md's "Existing DB adoption"
  section for what to do instead.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa40e596fcc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('plan_tier', sa.String(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_leads', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_leads_per_day', sa.Integer(), nullable=False),
    sa.Column('can_export', sa.Boolean(), nullable=True),
    sa.Column('can_use_ai', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.create_table('daily_lead_quota_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('leads_reserved', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'usage_date', name='uq_daily_lead_quota_org_date')
    )
    op.create_index(op.f('ix_daily_lead_quota_usage_id'), 'daily_lead_quota_usage', ['id'], unique=False)
    op.create_index(op.f('ix_daily_lead_quota_usage_organization_id'), 'daily_lead_quota_usage', ['organization_id'], unique=False)
    op.create_index(op.f('ix_daily_lead_quota_usage_usage_date'), 'daily_lead_quota_usage', ['usage_date'], unique=False)
    op.create_table('discovery_run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('requested_limit', sa.Integer(), nullable=True),
    sa.Column('businesses_returned', sa.Integer(), nullable=True),
    sa.Column('businesses_missing_website', sa.Integer(), nullable=True),
    sa.Column('websites_resolved_via_fallback', sa.Integer(), nullable=True),
    sa.Column('duplicates_removed', sa.Integer(), nullable=True),
    sa.Column('validated_leads', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_run_logs_id'), 'discovery_run_logs', ['id'], unique=False)
    op.create_index(op.f('ix_discovery_run_logs_organization_id'), 'discovery_run_logs', ['organization_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('invoice_pdf', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_invoice_id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_id'), 'usage_records', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('about_text', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_title', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('twitter_url', sa.String(), nullable=True),
    sa.Column('facebook_url', sa.String(), nullable=True),
    sa.Column('employees', sa.String(), nullable=True),
    sa.Column('revenue_band', sa.String(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('qualification_label', sa.String(), nullable=True),
    sa.Column('scrape_confidence', sa.Float(), nullable=True),
    sa.Column('email_confidence', sa.Float(), nullable=True),
    sa.Column('enrichment_confidence', sa.Float(), nullable=True),
    sa.Column('enrichment_source', sa.String(), nullable=True),
    sa.Column('email_source', sa.String(), nullable=True),
    sa.Column('scrape_source', sa.String(), nullable=True),
    sa.Column('outreach_message', sa.Text(), nullable=True),
    sa.Column('outreach_sent', sa.Boolean(), nullable=True),
    sa.Column('outreach_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'website', name='uq_leads_org_website')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('active_pipeline_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', name='uq_active_pipeline_lock_lead_id')
    )
    op.create_index(op.f('ix_active_pipeline_locks_id'), 'active_pipeline_locks', ['id'], unique=False)
    op.create_index(op.f('ix_active_pipeline_locks_organization_id'), 'active_pipeline_locks', ['organization_id'], unique=False)
    op.create_table('ai_decision_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('grounding_score', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('prompt_name', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('evaluation_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_decision_logs_id'), 'ai_decision_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_decision_logs_pipeline_id'), 'ai_decision_logs', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_ai_decision_logs_stage'), 'ai_decision_logs', ['stage'], unique=False)
    op.create_table('evaluation_report_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('grounding', sa.Float(), nullable=True),
    sa.Column('consistency', sa.Float(), nullable=True),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('evaluation_version', sa.String(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_report_logs_id'), 'evaluation_report_logs', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_report_logs_lead_id'), 'evaluation_report_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_evaluation_report_logs_organization_id'), 'evaluation_report_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_evaluation_report_logs_pipeline_id'), 'evaluation_report_logs', ['pipeline_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_lead_id'), 'jobs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_jobs_organization_id'), 'jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_jobs_pipeline_id'), 'jobs', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('lead_enrichment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('enrichment_type', sa.String(), nullable=False),
    sa.Column('enrichment_data', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_enrichment_logs_id'), 'lead_enrichment_logs', ['id'], unique=False)
    op.create_index(op.f('ix_lead_enrichment_logs_organization_id'), 'lead_enrichment_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lead_enrichment_logs_pipeline_id'), 'lead_enrichment_logs', ['pipeline_id'], unique=False)
    op.create_table('pipeline_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('final_status', sa.String(), nullable=False),
    sa.Column('stage_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_execution_logs_final_status'), 'pipeline_execution_logs', ['final_status'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_logs_id'), 'pipeline_execution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_logs_lead_id'), 'pipeline_execution_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_logs_organization_id'), 'pipeline_execution_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_logs_pipeline_id'), 'pipeline_execution_logs', ['pipeline_id'], unique=True)
    op.create_table('prompt_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('prompt_name', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_execution_logs_id'), 'prompt_execution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_execution_logs_lead_id'), 'prompt_execution_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_prompt_execution_logs_organization_id'), 'prompt_execution_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_prompt_execution_logs_pipeline_id'), 'prompt_execution_logs', ['pipeline_id'], unique=False)
    op.create_table('scraping_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('scraping_method', sa.String(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('scraped_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_logs_id'), 'scraping_logs', ['id'], unique=False)
    op.create_index(op.f('ix_scraping_logs_organization_id'), 'scraping_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scraping_logs_pipeline_id'), 'scraping_logs', ['pipeline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraping_logs_pipeline_id'), table_name='scraping_logs')
    op.drop_index(op.f('ix_scraping_logs_organization_id'), table_name='scraping_logs')
    op.drop_index(op.f('ix_scraping_logs_id'), table_name='scraping_logs')
    op.drop_table('scraping_logs')
    op.drop_index(op.f('ix_prompt_execution_logs_pipeline_id'), table_name='prompt_execution_logs')
    op.drop_index(op.f('ix_prompt_execution_logs_organization_id'), table_name='prompt_execution_logs')
    op.drop_index(op.f('ix_prompt_execution_logs_lead_id'), table_name='prompt_execution_logs')
    op.drop_index(op.f('ix_prompt_execution_logs_id'), table_name='prompt_execution_logs')
    op.drop_table('prompt_execution_logs')
    op.drop_index(op.f('ix_pipeline_execution_logs_pipeline_id'), table_name='pipeline_execution_logs')
    op.drop_index(op.f('ix_pipeline_execution_logs_organization_id'), table_name='pipeline_execution_logs')
    op.drop_index(op.f('ix_pipeline_execution_logs_lead_id'), table_name='pipeline_execution_logs')
    op.drop_index(op.f('ix_pipeline_execution_logs_id'), table_name='pipeline_execution_logs')
    op.drop_index(op.f('ix_pipeline_execution_logs_final_status'), table_name='pipeline_execution_logs')
    op.drop_table('pipeline_execution_logs')
    op.drop_index(op.f('ix_lead_enrichment_logs_pipeline_id'), table_name='lead_enrichment_logs')
    op.drop_index(op.f('ix_lead_enrichment_logs_organization_id'), table_name='lead_enrichment_logs')
    op.drop_index(op.f('ix_lead_enrichment_logs_id'), table_name='lead_enrichment_logs')
    op.drop_table('lead_enrichment_logs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_pipeline_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_organization_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_lead_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_evaluation_report_logs_pipeline_id'), table_name='evaluation_report_logs')
    op.drop_index(op.f('ix_evaluation_report_logs_organization_id'), table_name='evaluation_report_logs')
    op.drop_index(op.f('ix_evaluation_report_logs_lead_id'), table_name='evaluation_report_logs')
    op.drop_index(op.f('ix_evaluation_report_logs_id'), table_name='evaluation_report_logs')
    op.drop_table('evaluation_report_logs')
    op.drop_index(op.f('ix_ai_decision_logs_stage'), table_name='ai_decision_logs')
    op.drop_index(op.f('ix_ai_decision_logs_pipeline_id'), table_name='ai_decision_logs')
    op.drop_index(op.f('ix_ai_decision_logs_id'), table_name='ai_decision_logs')
    op.drop_table('ai_decision_logs')
    op.drop_index(op.f('ix_active_pipeline_locks_organization_id'), table_name='active_pipeline_locks')
    op.drop_index(op.f('ix_active_pipeline_locks_id'), table_name='active_pipeline_locks')
    op.drop_table('active_pipeline_locks')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_records_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_discovery_run_logs_organization_id'), table_name='discovery_run_logs')
    op.drop_index(op.f('ix_discovery_run_logs_id'), table_name='discovery_run_logs')
    op.drop_table('discovery_run_logs')
    op.drop_index(op.f('ix_daily_lead_quota_usage_usage_date'), table_name='daily_lead_quota_usage')
    op.drop_index(op.f('ix_daily_lead_quota_usage_organization_id'), table_name='daily_lead_quota_usage')
    op.drop_index(op.f('ix_daily_lead_quota_usage_id'), table_name='daily_lead_quota_usage')
    op.drop_table('daily_lead_quota_usage')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
